---
# Source: certs/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certs
---
# Source: certs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certs
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "create", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list"]
---
# Source: certs/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certs
subjects:
- kind: ServiceAccount
  name: certs
  namespace: "${NAMESPACE}"
roleRef:
  kind: ClusterRole
  name: certs
  apiGroup: rbac.authorization.k8s.io
---
# Source: certs/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: certs
  labels:
    app: certs
    chart: certs-1.1.14
    release: certs
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: certs
        release: certs
    spec:
      serviceAccountName: certs
      containers:
      - name: certs
        image: atmosx/arm64v8-certs:1.1.14
        imagePullPolicy: IfNotPresent
        env:
        - name: ACME_MANAGE_ALL_NAMESPACES
          value: "true"
        - name: ACME_NAMESPACES_WHITELIST
          value: ""
        - name: ACME_DEMO_ENABLED
          value: "false"
        - name: ACME_DEBUG
          value: "true"
        - name: AWS_ACCESS_KEY_ID
          value: ${AWS_ACCESS_KEY_ID}
        - name: AWS_SECRET_ACCESS_KEY
          value: ${AWS_SECRET_ACCESS_KEY}
        - name: AWS_DEFAULT_REGION
          value: eu-central-1
      restartPolicy: Never
---
# Source: certs/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: certs
  labels:
    app: certs
    chart: certs-1.1.13
    release: certs
spec:
  schedule: "0 0,12 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: certs
        release: certs
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      ttlSecondsAfterFinished: 120
      template:
        spec:
          serviceAccountName: certs
          containers:
          - name: certs
            image: atmosx/arm64v8-certs:1.1.12
            imagePullPolicy: IfNotPresent
            env:
            - name: ACME_MANAGE_ALL_NAMESPACES
              value: "true"
            - name: ACME_NAMESPACES_WHITELIST
              value: ""
            - name: ACME_DEMO_ENABLED
              value: "false"
            - name: ACME_DEBUG
              value: "true"
            - name: AWS_ACCESS_KEY_ID
              value: ${AWS_ACCESS_KEY_ID}
            - name: AWS_SECRET_ACCESS_KEY
              value: ${AWS_SECRET_ACCESS_KEY}
            - name: AWS_DEFAULT_REGION
              value: eu-central-1
          restartPolicy: Never
