version: '3.3'

services:
   mysql56:
     image: mysql:5.6
     volumes:
       - mysqlVolume:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: pass123
       MYSQL_DATABASE: db
       MYSQL_USER: user
       MYSQL_PASSWORD: pass345
volumes:
    mysqlVolume: {}
